setting_groups:
  auth:
    parent: core


setting_schemas:
  global:
    auth_logout_redirect_url:
      priority: 10
      group_key: auth
      category_key: auth_common
      type: string
      default: /
      validators: url

    auth_user_initial_groups:
      priority: 20
      group_key: auth
      category_key: auth_common
      type: combobox
      values: usergroups
      default: [ members, unconfirmed_email ]

    auth_confirm_email_period:
      priority: 30
      group_key: auth
      category_key: auth_common
      type: number
      default: 72

    auth_reset_password_period:
      priority: 40
      group_key: auth
      category_key: auth_common
      type: number
      default: 3
