users:
  avatars:
    extensions: [ jpg, jpeg ]
    jpeg_quality: 85

    resize:
      orig:
        width: 150
        height: 150
      md:
        width: 100
        height: 100
      sm:
        width: 30
        height: 30
