options:
  users:
    avatars:
      extentions: [ jpg, jpeg ]
      jpeg_quality: 85
      max_size: 100000

      resize:
        orig:
          width: 100
          height: 100
        md:
          width: 50
          height: 50
          type: png
          from: md
