users:
  avatars:
    extentions: [ jpg, jpeg ]
    jpeg_quality: 75

    resize:
      orig:
        width: 150
        height: 150
      md:
        width: 100
        height: 100
        unsharp: true
      sm:
        width: 30
        height: 30
        unsharp: true
