# Use this template to add custom infractions and penalties.
#
#    users:
#      infractions:
#
#        types:
#          overquoting:
#            points: 1
#            category_key: forum
#            expire_days: 30
#            priority: 10
#
#        penalties:
#          -
#            points: 7
#            action: to_violators
#            action_data: { days: 7 }
#          -
#            points: 14
#            action: to_violators
#            action_data: { days: 14 }
#          -
#            points: 30
#            action: to_violators
#            action_data: { days: 30 }
#          -
#            points: 60
#            action: to_violators
#            action_data: { days: 60 }
#          -
#            points: 90
#            action: to_violators
#            action_data: { days: 90 }
#          -
#            points: 100
#            action: to_banned
