users:
  member_page:

    menu:
      messages:
        to: users.messages
        priority: 10
      albums:
        to: users.albums_root
        priority: 20
      blog:
        to: blogs.member
        priority: 50
      bookmarks:
        to: users.bookmarks
        priority: 80
      drafts:
        to: users.drafts
        priority: 90
      settings:
        to: users.member.settings
        priority: 100

    # Blocks will be in users.member.blocks
    blocks:
      notepad:
        priority: 10
      user_info:
        priority: 20
      last_albums:
        priority: 30
      last_photos:
        priority: 40
      friends:
        priority: 50
      bookmarks:
        priority: 60
