users:
  member_page:

    menu:
      feed:
        to: users.feed
        priority: 10
      messages:
        to: users.messages
        priority: 20
      albums:
        to: users.albums_root
        priority: 30
      groups:
        to: groups
        priority: 40
      blog:
        to: blogs.member
        priority: 50
      bookmarks:
        to: users.bookmarks
        priority: 60
      subscribtions:
        to: users.subscriptions.index
        priority: 70
      drafts:
        to: users.drafts
        priority: 80
      settings:
        to: users.settings.index
        priority: 100

    # Blocks will be in users.member.blocks
    blocks:
      notepad:
        priority: 10
      about:
        priority: 20
      albums:
        priority: 30
      medias:
        priority: 40
      blog:
        priority: 50
      friends:
        priority: 60
      bookmarks:
        priority: 70
