menus:
  common:
    navbar:
      profile:
        to: users.profile
        priority: 10
        submenu:
          news:
            to: users.profile
          messages:
            to: users.profile
          albums:
            to: users.profile.albums_redirect
          clubs:
            to: users.profile
          bookmarks:
            to: users.profile
  admin:
    navbar:
      users:
        to: admin.users.usergroups.index
        submenu:
          usergroups:
            to: admin.users.usergroups.index
          members:
            to: admin.users.members.search
