menus:
  common:
    navbar:
      profile:
        to: users.profile
        priority: 10
  admin:
    navbar:
      users:
        to: admin.users.usergroups.index
        submenu:
          usergroups:
            #to: admin.users.usergroups.index
            submenu:
              manage:
                to: admin.users.usergroups.index
              add:
                to: admin.users.usergroups.add
