menus:
  common:
    navbar:
      profile:
        to: users.profile
        priority: 10
  admin:
    navbar:
      users:
        to: admin.users.index
      usergroups:
        to: admin.users.usergroups.index
