menus:
  common:
    navbar:
      profile:
        to: users.profile
        priority: 10
  admin:
    navbar:
      users:
        to: admin.users.usergroups.index
        submenu:
          usergroups:
            submenu:
              show:
                to: admin.users.usergroups.index
          members:
            submenu:
              search:
                to: admin.users.members.search
              add:
                to: admin.users.members.add
