menus:
  common:
    navbar:
      profile:
        to: users.profile
        priority: 10
  admin:
    navbar:
      users:
        to: admin.users.users.index
        submenu:
          users:
            to: admin.users.users.index
            submenu:
              manage: 
                to: admin.users.users.index
              add:
                to: admin.users.users.index # FIXME
          usergroups:
            to: admin.users.usergroups.index
            submenu:
              manage:
                to: admin.users.usergroups.index
              add:
                to: admin.users.usergroups.add
