menus:
  common:
    navbar:
      profile:
        to: users.profile_redirect
        priority: 10
  admin:
    navbar:
      users:
        to: admin.users.usergroups.index
        submenu:
          usergroups:
            to: admin.users.usergroups.index
          members:
            to: admin.users.members.search
