users:
  profile_page:

    actions:
      usernote:
        priority: 10
      ignore:
        priority: 20
      mod_divider:
        priority: 30
      hellban:
        priority: 40
      add_mod_note:
        priority: 50

    menu:
      dialogs:
        to: users.dialogs_root
        priority: 20
      subscribtions:
        to: users.subscriptions.index
        priority: 30
      #albums:
      #  to: users.albums_root
      #  priority: 40
      #groups:
      #  to: groups
      #  priority: 50
      #blog:
      #  to: blogs.member
      #  priority: 60
      bookmarks:
        to: users.bookmarks
        priority: 70
      #drafts:
      #  to: users.drafts
      #  priority: 80
      settings:
        to: users.settings.general
        priority: 100

    # Blocks will be in users.member.blocks
    blocks:
      about:
        priority: 20
      blog:
        priority: 30
      bookmarks:
        priority: 40

      # Second column (priority > 100)
      albums:
        priority: 110
      medias:
        priority: 120
