router:
  http.get:
    users.profile:
      "/profile": ~

    users.member:
      "/member{id}":
        id: /\d+/

    admin.users.usergroups.index:
      "/usergroups": ~

    admin.users.usergroups.new:
      "/usergroups/new": ~

    admin.users.usergroups.edit:
      "/usergroups/edit/{_id}":
        _id: /\w+/

    admin.users.members.search:
      "/members/search": ~

    users.auth.login.show:
      "/auth/login": ~

    users.auth.reset_password.request_show:
      "/auth/reset": ~

    users.auth.reset_password.request_done_show:
      "/auth/reset/sent": ~

    users.auth.reset_password.change_show:
      "/auth/reset/{secret_key}":
        secret_key: /[0-9a-f]+/

    users.auth.reset_password.change_done_show:
      "/auth/reset/done":

    users.auth.register.show:
      "/auth/register": ~

    users.auth.register.done_show:
      "/auth/register/done": ~

    users.auth.register.resend_activation_show:
      "/auth/register/resend": ~

    users.auth.register.activate_show:
      "/auth/register/activate/{secret_key}":
        secret_key: /[0-9a-f]+/
