router:
  map:
    users.profile:
      "/profile": ~

    users.member:
      "/member{id}":
        id: /\d+/

    admin.users.usergroups.index:
      "/usergroups": ~

    admin.users.usergroups.add:
      "/usergroups/add": ~

    admin.users.usergroups.edit:
      "/usergroups/edit/{_id}":
        _id: /\w+/

    admin.users.members.search:
      "/members": ~

    users.auth.login.show:
      "/auth/login": ~

    users.auth.logout.exec:
      "/auth/logout": ~

    users.auth.register.show:
      "/auth/reg": ~

    users.auth.register.success:
      "/auth/reg/done": ~
