router:
  http.get:
    users.profile:
      "/profile": ~

    users.member:
      "/member{id}":
        id: /\d+/

    admin.users.usergroups.index:
      "/usergroups": ~

    admin.users.usergroups.new:
      "/usergroups/new": ~

    admin.users.usergroups.edit:
      "/usergroups/edit/{_id}":
        _id: /\w+/

    admin.users.members.search:
      "/members/search": ~

    users.auth.login.show:
      "/auth/login": ~

    users.auth.reset_password.show:
      "/auth/reset": ~

    users.auth.reset_password:
      "/auth/reset/{user_id}/{secret_key}":
        user_id: /[0-9a-f]+/
        secret_key: /[0-9a-f]+/

    users.auth.register.show:
      "/auth/register": ~

    users.auth.confirm_email.request:
      "/auth/confirm": ~

    users.auth.confirm_email:
      "/auth/confirm/{user_id}/{secret_key}":
        user_id: /[0-9a-f]+/
        secret_key: /[0-9a-f]+/
