router:
  map:
    users.profile:
      "/profile": ~

    users.member:
      "/member{id}":
        id: /\d+/

    admin.users.index:
      "/users": ~


    users.auth.login.view:
      "/auth/login": ~

    users.auth.logout:
      "/auth/logout": ~

    users.auth.register.view:
      "/auth/reg": ~

    users.auth.register.success:
      "/auth/reg/done": ~
