router:
  map:
    users.profile:
      "/profile": ~

    users.member:
      "/member{id}":
        id: /\d+/

    admin.users.index:
      "/users": ~


    users.auth.login.show:
      "/auth/login": ~

    users.auth.logout:
      "/auth/logout": ~

    users.auth.register.show:
      "/auth/reg": ~

    users.auth.register.success:
      "/auth/reg/done": ~

    admin.users.usergroups.index:
      "/usergroups": ~

    admin.users.usergroups.add:
      "/usergroups/add": ~

    admin.users.usergroups.edit:
      "/usergroups/edit/{short_name}":
        short_name: /\w+/
