router:
  http.get:
    users.profile:
      "/profile": ~

    #users.profile.news:
    #  "/news": ~

    #users.profile.messages:
    #  "/messages": ~

    users.profile.albums_redirect:
      "/albums": ~

    #users.profile.clubs:
    #  "/clubs": ~

    #users.profile.bookmarks:
    #  "/bookmarks": ~

    users.member:
      "/member{user_hid}":
        user_hid:
          match: /\d+/
          type: 'integer'

    users.member.albums:
      "/member{user_hid}/albums(/{album_id})(/{all_photos})":
        user_hid:
          match: /\d+/
          type: 'integer'
        album_id:
          match: /[0-9a-f]{24}/
          default: ''
        all_photos:
          match: /all/
          default: ''

    admin.core.user_lookup:
     "/user_lookup": ~

    admin.users.usergroups.index:
      "/usergroups": ~

    admin.users.usergroups.new:
      "/usergroups/new": ~

    admin.users.usergroups.edit:
      "/usergroups/edit/{_id}":
        _id: /[0-9a-f]{24}/

    admin.users.members.search:
      "/members/search": ~

    users.auth.login.show:
      "/auth/login": ~

    users.auth.reset_password.request_show:
      "/auth/reset": ~

    users.auth.reset_password.request_done_show:
      "/auth/reset/sent": ~

    users.auth.reset_password.change_show:
      "/auth/reset/{secret_key}":
        secret_key: /[0-9a-f]+/

    users.auth.reset_password.change_done_show:
      "/auth/reset/done":

    users.auth.register.show:
      "/auth/register": ~

    users.auth.register.done_show:
      "/auth/register/done": ~

    users.auth.register.resend_activation_show:
      "/auth/register/resend": ~

    users.auth.register.activate_show:
      "/auth/register/activate/{secret_key}":
        secret_key: /[0-9a-f]+/
