router:
  map:
    users.profile:
      "/profile": ~

    users.member:
      "/member{id}":
        id: /\d+/

    admin.users.index:
      "/users": ~

    users.auth.register.view:
      "/auth/reg": ~

    users.auth.register.exec:
      "/auth/reg/register": ~

    users.auth.login.view:
      "/auth/login": ~

    users.auth.login.email:
      "/auth/login/email": ~

    users.auth.logout:
      "/auth/logout": ~
