options:
  users:
    media_sizes:
      orig:
         width: 1024
         height: 768
      md:
        width: 200
        height: 150

    avatar_sizes:
      orig:
        width: 150
        height: 150
      md:
        width: 100
        height: 100
      sm:
        width: 55
        height: 55
        quality: 85 # (0 - 100)
