setting_groups:
  auth:
    parent: core


setting_schemas:
  global:
    auth_logout_redirect_url:
      priority: 10
      group_key: auth
      category_key: auth_common
      type: string
      default: /
      validators: url

    auth_reset_password_period:
      priority: 20
      group_key: auth
      category_key: auth_common
      type: number
      default: 3
