setting_groups:
  users: ~

  users_messages:
    parent: users

setting_schemas:
  global:
    general_login_expire_days:
      priority: 40
      group_key: general
      category_key: general_common
      type: number
      default: 7

    users_message_max_images:
      type: number
      group_key: users_messages
      category_key: messages_text
      default: 100

    users_message_max_emojis:
      type: number
      group_key: users_messages
      category_key: messages_text
      default: 20
