setting_schemas:
  global:
    general_security_policy:
      priority: 10
      group_key: general
      category_key: general_common
      type: dropdown
      values:
      - https_for_registered: https_for_registered
      - https_only: https_only
      - http_only: http_only
      default: https_for_registered
