setting_schemas:
  global:
    general_ssl_mode:
      priority: 10
      group_key: general
      category_key: general_common
      type: dropdown
      values:
      - https_members: https_members
      - https_always:  https_always
      - https_off:     https_off
      default: https_members

    general_session_expire_hours:
      priority: 20
      group_key: general
      category_key: general_common
      type: number
      default: 168
