setting_groups:
  register:
    parent: core


setting_schemas:
  global:
    register_user_initial_group:
      priority: 10
      group_key: register
      category_key: register_common
      type: dropdown
      values: usergroups
      default: validating

    register_user_validated_group:
      priority: 20
      group_key: register
      category_key: register_common
      type: dropdown
      values: usergroups
      default: members
