setting_groups:
  register:
    parent: core


setting_schemas:
  global:
    validate_email:
      priority: 10
      group_key: register
      category_key: register_common
      type: boolean
      default: true

    registered_user_group:
      priority: 20
      group_key: register
      category_key: register_common
      type: dropdown
      values: usergroups
      default: members
