setting_schemas:
  usergroup:
    cannot_be_ignored:
      priority: 1020
      category_key: perm_users
      type: boolean
      default: false

    can_vote:
      priority: 1030
      category_key: perm_users
      type: boolean
      default: false

    users_can_upload_media:
      priority: 1040
      category_key: perm_users
      type: boolean
      default: false

    users_media_total_quota_mb:
      priority: 1050
      category_key: perm_users
      type: number
      default: 1024

    users_media_single_quota_kb:
      priority: 1060
      category_key: perm_users
      type: number
      default: 2048

    can_receive_email:
      priority: 1070
      category_key: perm_users
      type: boolean
      default: false

    can_report_abuse:
      priority: 1080
      category_key: perm_users
      type: boolean
      default: false

    can_use_dialogs:
      priority: 1090
      category_key: perm_users
      type: boolean
      default: false

    can_create_dialogs:
      priority: 1100
      category_key: perm_users
      type: boolean
      default: false

    can_edit_profile:
      priority: 1110
      category_key: perm_users
      type: boolean
      default: false

    is_bot:
      priority: 1120
      category_key: perm_users
      type: boolean
      default: false

    can_access_acp:
      priority: 1990
      category_key: perm_admin
      type: boolean
      default: false

    can_hellban:
      priority: 2000
      category_key: perm_admin
      type: boolean
      default: false

    can_see_hellbanned:
      priority: 2010
      category_key: perm_admin
      type: boolean
      default: false

    can_see_deleted_users:
      priority: 2020
      category_key: perm_admin
      type: boolean
      default: false

    can_see_ip:
      priority: 2030
      category_key: perm_admin
      type: boolean
      default: false

    users_mod_can_delete_media:
      priority: 2040
      category_key: perm_admin
      type: boolean
      default: false

    cannot_receive_infractions:
      priority: 200
      category_key: perm_users
      type: boolean
      default: false

    can_see_infractions:
      priority: 2010
      category_key: perm_infractions
      type: boolean
      default: false

    can_delete_infractions:
      priority: 2020
      category_key: perm_infractions
      type: boolean
      default: false

    users_mod_can_add_infractions_profile:
      priority: 2030
      category_key: perm_infractions
      type: boolean
      default: false

    users_mod_can_add_infractions_dialogs:
      priority: 2040
      category_key: perm_infractions
      type: boolean
      default: false

    can_add_mod_notes:
      priority: 3010
      category_key: perm_mod_notes
      type: boolean
      default: false

    can_delete_mod_notes:
      priority: 3020
      category_key: perm_mod_notes
      type: boolean
      default: false

    mod_notes_edit_max_time:
      priority: 3030
      category_key: perm_mod_notes
      type: number
      default: 30
