setting_schemas:
  user:
    default_subscription_mode:
      priority: 10
      category_key: subscriptions
      type: dropdown
      values:
        - WATCHING
        - TRACKING
      default: TRACKING

    dialogs_notify:
      priority: 20
      category_key: dialogs
      type: boolean
      default: true
