setting_schemas:
  usergroup:
    can_access_acp:
      priority: 1000
      category_key: perm_admin
      type: boolean
      default: false

    can_see_hellbanned:
      priority: 1010
      category_key: perm_admin
      type: boolean
      default: false

    can_see_deleted_users:
      priority: 1020
      category_key: perm_admin
      type: boolean
      default: false
