setting_schemas:
  usergroup:
    can_vote:
      priority: 1030
      category_key: perm_users
      type: boolean
      default: true

    users_can_upload_media:
      priority: 1040
      category_key: perm_users
      type: boolean
      default: false

    users_media_total_quota_mb:
      priority: 1050
      category_key: perm_users
      type: number
      default: 1024

    users_media_single_quota_kb:
      priority: 1060
      category_key: perm_users
      type: number
      default: 2048

    can_receive_email:
      priority: 1070
      category_key: perm_users
      type: boolean
      default: true

    can_report_abuse:
      priority: 1080
      category_key: perm_users
      type: boolean
      default: false

    can_send_messages:
      priority: 1090
      category_key: perm_users
      type: boolean
      default: false

    can_access_acp:
      priority: 2000
      category_key: perm_admin
      type: boolean
      default: false

    can_see_hellbanned:
      priority: 2010
      category_key: perm_admin
      type: boolean
      default: false

    can_see_deleted_users:
      priority: 2020
      category_key: perm_admin
      type: boolean
      default: false

    can_see_ip:
      priority: 2030
      category_key: perm_admin
      type: boolean
      default: false

    can_receive_infractions:
      priority: 200
      category_key: perm_users
      type: boolean
      default: true

    can_see_infractions:
      priority: 2010
      category_key: perm_infractions
      type: boolean
      default: false

    can_delete_infractions:
      priority: 2020
      category_key: perm_infractions
      type: boolean
      default: false

    users_mod_can_add_infractions:
      priority: 2030
      category_key: perm_infractions
      type: boolean
      default: false
