setting_schemas:
  user:
    edit_no_mlinks:
      type: boolean
      default: false
      category_key: editor
    edit_no_emojis:
      type: boolean
      default: false
      category_key: editor
