setting_groups:
  content: ~

  votes:
    parent: content

setting_schemas:
  global:
    can_vote:
      priority: 10
      group_key: votes
      category_key: votes_common
      type: boolean
      default: true

    votes_add_max_time:
      priority: 20
      group_key: votes
      category_key: votes_common
      type: number
      default: 168 # one week (24 * 7)
