setting_groups:
  votes:
    parent: core

setting_schemas:
  global:
    votes_add_max_time:
      priority: 20
      group_key: votes
      category_key: votes_common
      type: number
      default: 168 # one week (24 * 7)
